tweetme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from tweets.views import TweetListView
from .views import home, searchView
from hashtags.views import HashTagView
from hashtags.api.views import TagTweetAPIView
from tweets.api.views import SearchTweetAPIView
from accounts.views import UserRegisterView

urlpatterns = [
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TweetListView.as_view(), name='home'),
    url(r'^search/$', searchView.as_view(), name='search'),
    url(r'^api/search/$', SearchTweetAPIView.as_view(), name='search-api'),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagTweetAPIView.as_view(), name='tag-tweet-api'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    url(r'^', include('accounts.urls', namespace='profiles')),
    url(r'^api/', include('accounts.api.urls', namespace='profiles-api')),
   
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view() , name='hashtag'),
 
    
  


]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tweets/urls.py
from django.conf.urls import url
from django.views.generic.base  import RedirectView
from .views import  (
    RetweetView,
	TweetCreateView,
	TweetListView, 
	TweetDetailView,
    TweetUpdateView,
    TweetDeleteView
	)
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/")), #/tweet/
    url(r'^search/$', TweetListView.as_view(), name='list'), #/tweet/
    url(r'^create/$', TweetCreateView.as_view(), name='create'), #/tweet/create/
    
      # url(r'^(?P<pk>\d+)/$', tweet_detail_view, name='detail'),
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'), #tweet/1
    url(r'^(?P<pk>\d+)/retweet/$', RetweetView.as_view(), name='detail'), #/tweet/1/update
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'), #/tweet/1/update
    url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'), #/tweet/1/delete
    #url(r'^tweet/', include('tweets.urls')),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
   
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
      function getParameterByName(name, url) {
      if (!url) url = window.location.href;
      name = name.replace(/[\[\]]/g, "\\$&");
      var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
          results = regex.exec(url);
      if (!results) return null;
      if (!results[2]) return '';
      return decodeURIComponent(results[2].replace(/\+/g, " "));
    }
function loadTweetContainer(tweetContainerID, fetchOneId){

    console.log("heloooo");
       var query = getParameterByName('q');  
       var tweetList = [];
       var nextTweetUrl;
       var initialURL = "/api/tweet/"; 
       var tweetContainer;
       console.log(tweetContainerID)
       if (tweetContainerID){
        tweetContainer = $("#" + tweetContainerID)
       }else{
        tweetContainer = $("#tweet-container")
       }
       var initialURL = tweetContainer.attr("data-url") || "/api/tweet/"
       console.log(initialURL)

      $(document.body).on("click", ".tweet-like", function(e){
          e.preventDefault();
       
          var this_ = $(this);
          var tweetId = this_.attr("data-id");
          var likedUrl = '/api/tweet/' + tweetId + "/like/";

        $.ajax({
         url: likedUrl,
         method:"GET",
         success: function(data){
          if (data.liked){
            this_.text("Liked")

          }else
          {
             this_.text("UnLiked")
           }
         },
         error: function(data){
          console.log("error")
          console.log(data)
         }
        
      });
         });
    
        $(document.body).on("click", ".tweet-reply", function(e){
        e.preventDefault()
        var this_ =$(this)
        var parentId = this_.attr("data-id")
        var username = this_.attr("data-user")
        var content = this_.parent().parent().find(".content").text();
        $("#replyModal").modal({})
         $("#replyModal textarea").after("<input type='hidden' value='"+ parentId + "'name='parent_id' />")
                  $("#replyModal textarea").after("<input type='hidden' value='"+ true + "'name='reply' />")

        $("#replyModal textarea").val("@" + username + " ")
         $("#replyModal #replyModalLabel").text("Reply to" + content + " ")
        $("#replyModal").on("shown.bs.modal", function(){
          console.log("hide")
           $('textarea').focus()


        })
            // var url = "/api" + $(this).attr("href");
            // $.ajax({
            //  url: url,
            //  method:"GET",
            //  success: function(data){
            //   console.log(data)
            //   if (initialURL == "/api/tweet/")
            //     attachTweet(data, true, true);
            //     updateHashLinks();
            //  },
            //  error: function(data){
            //   console.log("error")
            //   console.log(data)
            //  }
          

       });
      


       $(document.body).on("click", ".retweetBtn", function(e){
        e.preventDefault()
        
        var url = "/api" + $(this).attr("href");
        $.ajax({
         url: url,
         method:"GET",
         success: function(data){
          console.log(data)
          if (initialURL == "/api/tweet/")
            attachTweet(data, true, true);
            updateHashLinks();
         },
         error: function(data){
          console.log("error")
          console.log(data)
         }
          

       });
       });

       function updateHashLinks()
       {
        $(".content").each(function(data){
          var hashtagRegex = /(^|\s)#([\w\d-]+)/g;
          var usernameRegex = /(^|\s)@([\w\d-]+)/g;
          var newText;
          var currentHtml=$(this).html();
          newText = currentHtml.replace(hashtagRegex, "$1<a href='/tags/$2'>#$2</a>")
          $(this).html(newText);
          newText = $(this).html().replace(usernameRegex, "$1 @<a href='/$2'>$2</a>")
          $(this).html(newText);

        });
       }

       function formatTweet(tweetValue){

       
            var retweet;
            var preContent;
            var container;
            var isReply = tweetValue.reply;
            var replyId = tweetValue.id
            if (tweetValue.parent){
              replyId = tweetValue.parent.id
            }
            var openingContainerDiv = "<div class=\"media\">"
            if (tweetValue.id == fetchOneId){
              openingContainerDiv = "<div class=\"media media-focus\">"
              setTimeout(function(){
                $('.media-focus').css("background-color", '#fff')

              }, 5000);
            }
            if (tweetValue.parent && !isReply){
              tweetValue = tweetValue.parent
              preContent = "<span class='grey-color'>Retweet via" + tweetValue.user.username +"on"+ tweetValue.datedisplay+"</span ><br/>"
            }else if(tweetValue.parent && isReply){
              // tweetValue = tweetValue.parent
              preContent = "<span class='grey-color'>Reply to @" + tweetValue.parent.user.username +"</span ><br/>"
            }

             var verb = 'Like'
            if (tweetValue.did_likes){
              verb = 'Unlike'
            }

          var tweetContent = "<span class='content'>"+tweetValue.content+"</span><br/> via <a href='" + tweetValue.user.url+"'>" + tweetValue.user.username +" </a>| "+ tweetValue.date_display + " | " + " <a href='/tweet/"+tweetValue.id+"'>View</a> | "+"<a class='retweetBtn' href='/tweet/"+tweetValue.id+"/retweet/'>Retweet</a>" + " | <a class='tweet-like' data-id=" + tweetValue.id + " >  " + verb +"("+ tweetValue.likes +") </a>" + " | <a class='tweet-reply' data-user='" + tweetValue.user.username + "'data-id=" + tweetValue.id + " >Reply</a>";

          if (preContent){
              container = openingContainerDiv + "<div class=\"media-body\">"+ preContent + tweetContent +"</div></div><hr/>";
          }else{
              container = openingContainerDiv + "<div class=\"media\"><div class=\"media-body\">"+ tweetContent +"</div></div><hr/>";
          }
          return container;
       }

       function attachTweet(tweetvalue, preprend, retweet){
        
            // alert(value.user);alert(value.content);return false;
            var user = tweetvalue.user;
            var tweetuser = tweetvalue.user;
            var tweetcontent = tweetvalue.content;
            var datedisplay = tweetvalue.date_display;
            var tweet_format;
            var verb = 'Like'
            if (tweetvalue.did_likes){
              verb = 'Unlike'
            }
          
            // var isRetweet = tweetvalue.is_retweet;
            tweet_format = formatTweet(tweetvalue)

            if(preprend==true)
            {
              tweetContainer.prepend(tweet_format);
            }
            else
            {
              tweetContainer.append(tweet_format);
            }
            
       }
    
      function parseTweets()
      {
        if(tweetList == 0)
        {
          tweetContainer.text("No Tweets Found")
        }
        else
        {
        $.each(tweetList, function(key, value){
          
          var tweetkey = key;
          if(value.parent)
          {
            attachTweet(value, false, true)
          }else{
            attachTweet(value)
          }
          
        });
          }
      }


      function fetchTweets(Url)
      {
        // console.log(fetching....)
        var fetchUrl;
        if(!Url){
          fetchUrl = initialURL;
        }else{
          fetchUrl = Url;
        }
      $.ajax({
         url: fetchUrl,
         data:{
          "q": query
         },
         // url: "{% url 'tweet-api:list' %}",
         method:"GET",
         success: function(data){
          console.log(data)
          tweetList = data.results;
          if(data.next)
          {
            nextTweetUrl = data.next
          }else{
            $("#loadmore").css("display", "none")
          }
          // nextTweetUrl = data.next;
          parseTweets();
          updateHashLinks();
         
         },
         error: function(data){
          console.log("error");
          console.log(data);
         }
        });
      }

      function fetchSingle(fetchOneId)
      {
         
     
        var fetchDetaillUrl = "/api/tweet/"+fetchOneId+ "/";
        // alert(fetchDetaillUrl);
    
      $.ajax({
         url: fetchDetaillUrl,      
         method:"GET",
         success: function(data){
          console.log("check");
          console.log(data)
          tweetList = [data];
          // if(data.next)
          // {
          //   nextTweetUrl = data.next
          // }else{
          //   $("#loadmore").css("display", "none")
          // }
          // nextTweetUrl = data.next;
          parseTweets();
          updateHashLinks();
         
         },
         error: function(data){
          console.log("error");
          console.log(data);
         }
        });
      }
        if(fetchOneId)
        {
          
           fetchSingle(fetchOneId);
        }
        else
        {

           fetchTweets()
        }
       

        $("#loadmore").click(function(event){
          event.preventDefault()
          if (nextTweetUrl){
            fetchTweets(nextTweetUrl)
          }
        })

        var charsStart = 140;
        var charsCurrent = 0;
        $(".tweet-form").append("<span class='tweetCharsLeft' style='margin-left: 20px !important'>"+ charsStart +"</span>");

         $(".tweet-form textarea").keyup(function(event){
          var tweetValue = $(this).val();
          // consloe.log(tweetvalue);
          charsCurrent = charsStart - tweetValue.length
          // $("#tweetCharsLeft").text(charsCurrent);
          var spanChars = $(this).parent().parent().parent().find("span.tweetCharsLeft");
          spanChars.text(charsCurrent)
          if(charsCurrent > 0)
          {
            spanChars.removeClass("grey-color");
            spanChars.removeClass("red-color");
          }else if(charsCurrent == 0)
          {
            spanChars.removeClass("red-color");
            spanChars.addClass("grey-color");

          }else if(charsCurrent < 0)
          {
            spanChars.removeClass("grey-color");
            spanChars.addClass("red-color");

          }

         });

    $(".tweet-form").submit(function(event)
    {
      
      event.preventDefault()
      var this_ = $(this);
      console.log(event)
      //console.log(this_.serialize())
      var formData = this_.serialize();

      $.ajax({
         url: "/api/tweet/create/",
         data: formData,
         // url: "{% url 'tweet-api:list' %}",
         method:"POST",
         success: function(data){
          this_.find("input[type=text], textarea").val("")
          console.log(data)
          //tweetList = data;
          attachTweet(data, true)
          updateHashLinks()
          $("#replyModal").modal("hide")
         
         },
         error: function(data){
          console.log("error");
          console.log(data);
         }
        });

      
      

    });
}

    </script>
     <title>{% block title %} Tweetme.co  {% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">-->
  <style type="text/css">
    
  .red-color
  {
    color:red;
  }
    .grey-color
  {
    color:#CCC;
  }
  .media-focus{
    background-color: rgba(255, 255, 0, 0.22);
  }
  </style>
  </head>
  <body>
   <div class="container">
      {% include "navbar.html" %}
      {% block content %} 
      {% endblock content %}
   </div>
      {% include "reply-modal.html" %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" ></script>
     {% block script %}{% endblock script %}

     <script>
      $(document).ready(function(){
        var typingTimer;
        var doneInterval = 500 //in ms
        var searchInput = $("#navbar-search-form input[type=text]")
        var searchQuery;

        searchInput.keyup(function(event){
            searchQuery = $(this).val()
          //alert(searchQuery);
            console.log("searchquer"+searchQuery)

            clearTimeout(typingTimer)
            typingTimer = setTimeout(doneSearchTyping, doneInterval)
        })

          searchInput.keydown(function(event){
            clearTimeout(typingTimer)
            console.log(event.key)
        })

          function doneSearchTyping(){
           //alert();
            if (searchQuery){
              console.log("done typing")
              var url = '/search/?q=' + searchQuery
              document.location.href = url;
            }

          }
      })

     </script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
<!--     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" crossorigin="anonymous"></script>
 --><!--     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
 -->  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %} {{block.super }}  | Welcome {% endblock title%}

{% block content %} 
<h1> Hello world again!</h1>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Tweetme</a>
    </div>
    {% include 'tweets/search_form.html' %}    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    {% if request.user.is_authenticated %}

       <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ request.user.profile.get_absolute_url }}">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>

    {% else %}
    
      <ul class="nav navbar-nav navbar-right">
     
             <li><a href="{% url 'login' %}">Login</a></li>
               <li><a href="{% url 'register' %}">Register</a></li>
          </ul>
     
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/reply-modal.html
<!-- Modal -->
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form class="from tweet-form"> {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="replyModalLabel">Modal title</h5>
        </div>
      <div class="modal-body">
      
        <textarea id='tweetReplyArea' class='from-control' name='content'></textarea>
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       <input type="submit" class="btn btn-primary" value='reply'>
      </div>
      </form>
    </div>
  </div>
</div>

templates/search.html
{% extends "base.html" %}
 {% block script %}
 	<script type="text/javascript">
	
 	

	$(document).ready(function(){
		loadTweetContainer("tweet-container")


			});
	</script>
 {% endblock script %}


{% block content %} 

		
	<div class="row">
		<div class="col-sm-12">
			{% if request.GET.q %}
			<p class="lead">Results for {{ request.GET.q }}</p>
			{% endif %}
		</div>
		
		<div class="col-sm-9">
				<h1>Tweets</h1>
			{% if not request.GET.q %}
				<div class="">
					
					{% include "tweets/form.html" with form=create_form action_url=create_url btn_title="Tweet" form_class='tweet-form' %}
				
				</div>
 				<hr/>
	 		{% endif %}
	 			<div id="tweet-container" data-url="/api/search/">
	 				
	 			</div>

	 			<a href="#" id="loadmore">Load More Tweets</a>
				
		</div>
		<div class='col-sm-3'>
			<h1>User</h1>
			{% for user in users %}
			<a href="/{{user.username}}/">{{user.username}}</a><br/>
			{% empty%}
			<p> No user found</p>
			{% endfor %}
		</div>
	</div>
{% endblock content %}



<!-- {% for object in object_list %}
				<div class="media">
				  <div class-="media-left">
				  	<a href="#">
				  	  {% if object.image %}
				        <img class="media-object" src="..." alt="..."/>
				  	  {% endif %}
				    </a>
				  </div>
				  <div class="media-body">
				    	{{ object.content }}<br/>
				    	via {{ object.user }}  | {{ object.timestamp | timesince}} ago | <a href='{{ object.get_absolute_url }}'>View</a>
				  </div>
				</div>
		        </hr>

			 {% empty %}
			    {% if request.GET.q %}
				 <p>No tweets Found</p>
				{% else %}
				 <p>No tweets yet</p>
				{% endif %}
		    {% endfor %} -->